# Copyright (c) https://github.com/UWU-TEAM 2025-present
# Copyright (c) https://github.com/linastorvaldz 2025-present

name: "TeamWin Recovery Builder"
description: "Build TWRP with Github Action"
author: "linastorvaldz"

branding:
  icon: 'terminal'
  color: 'yellow'

inputs:
  TWRP_SYNC_BRANCH:
    description: 'Manifest Branch'
    type: string
    default: '12.1'
  DEVICE_TREE:
    description: 'Device tree repository'
    type: string
  DEVICE_TREE_BRANCH:
    description: 'Device tree branch'
    type: string
  DEVICE_PATH:
    description: 'Path to device tree'
    type: string
  DEVICE_CODENAME:
    description: 'Device codename'
    type: string
  BUILD_TARGET:
    description: 'Specify Your Build Target [boot,recovery,vendor_boot]'
    type: string
  TG_CHAT_ID:
    description: 'Telegram Chat ID'
    type: string
  TG_TOKEN:
    description: 'Telegram Bot Token'
    type: string
  TIMEZONE:
    description: 'Specify Your Timezone'
    type: string
    default: 'Asia/Makassar'

runs:
  using: 'composite'
  steps:

    - name: Cleanup
      uses: mehyaa/slimhub_actions@fix/toolset-url

    - name: Set swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Set GitHub Path
      shell: bash
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Prepare Build Environment
      shell: bash
      run: |
        git clone --depth=1 https://github.com/akhilnarang/scripts -b master .sc
        sudo bash .sc/setup/android_build_env.sh
        sleep 1
        sudo timedatectl set-timezone "${{ inputs.TIMEZONE }}"

    - name: Sync TWRP Manifest
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        mkdir -p ${GITHUB_ACTION_PATH}/TWRP
        cd ${GITHUB_ACTION_PATH}/TWRP

        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-${{ inputs.TWRP_SYNC_BRANCH }}
        repo sync -j$(nproc --all) --force-sync

        if [[ -n "${{ inputs.DEVICE_TREE }}" ]]; then
            git clone --depth=1 \
            ${{ inputs.DEVICE_TREE }} \
            -b ${{ inputs.DEVICE_TREE_BRANCH }} \
            ${{ inputs.DEVICE_PATH }}
        fi

    - name: Build TeamWin Recovery
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
        TWRP_BRANCH: ${{ inputs.TWRP_SYNC_BRANCH }}
        DEVICE_PATH: ${{ inputs.DEVICE_PATH }}
        CODENAME: ${{ inputs.DEVICE_CODENAME }}
        BUILD_TARGET: ${{ inputs.BUILD_TARGET }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        source functions.sh
        timeStart

        cd ${GITHUB_ACTION_PATH}/TWRP
        set +e
        source build/envsetup.sh

        export DEVICE=$(grep "PRODUCT_MODEL :=" ./$DEVICE_PATH/twrp_$CODENAME.mk -m 1 | cut -d = -f 2)
        export BUILD_LOG=$(realpath ./build.log)
        export OUT=$(realpath ./out/target/product/$CODENAME)

        lunch twrp_$CODENAME-eng
        sleep 5
        build_message "Building... 🛠️"
        _BUILD_TARGET=$(echo "$BUILD_TARGET" | tr -d '_')
        mka adbd ${_BUILD_TARGET}image -j$(nproc --all) 2>&1 | tee -a ${BUILD_LOG}
        export retVal=${PIPESTATUS[0]}
        timeEnd
        buildStatus

        export SHA1=$(sha1sum $OUT/$BUILD_TARGET.img | cut -d ' ' -f1)
        export MD5=$(md5sum $OUT/$BUILD_TARGET.img | cut -d ' ' -f1)
        export LINK="https://github.com/${{ github.repository }}/releases/tag/${BUILD_DATE}"

        sleep 2
        create_release_notes
        gh release create \
            "$BUILD_DATE" \
            $OUT/$BUILD_TARGET.img \
            --title "TWRP for ${DEVICE} (${CODENAME}) // ${BUILD_DATE}" \
            -F "${GITHUB_ACTION_PATH}/release-notes.md" \
            -R "${{ github.repository }}"
        sleep 1
        build_success_msg
